import { Providers } from "@/app/providers";
import "./admin.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className="mh-admin">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
