import { Providers } from "./providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mh-main">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
